driver:
  desiredCapabilities:
    browserName: <%= env.BROWSER || 'firefox' %>
    safari.options:
      cleanSession: true
      ensureCleanSession: true
  screenshots: screenshots

implicitWait: 5000
baseUrl: https://www.shopbeam.com

# spawn a selenium server as child process
spawnSelenium: true
